services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=realestate
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  data_downloader:
    build:
      context: ./data_downloader
    depends_on:
      - db

  backend:
    build: 
      context: ./backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/realestate

  frontend:
    depends_on:
      - backend

volumes:
  postgres_data: