services:
  db:
    container_name: asi_db_prod
    restart: always

  data_downloader:
    container_name: asi_downloader_prod
    build:
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/realestate

  backend:
    container_name: asi_backend_prod
    build: 
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    restart: always
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    container_name: asi_frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: always