services:
  db:
    container_name: asi_db_test
    environment:
      - POSTGRES_DB=realestate_test
    ports:
      - "5433:5432"

  backend:
    container_name: asi_backend_test
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DB_NAME=realestate_test
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - TZ=Europe/Warsaw
    volumes:
      - ./backend:/app
    command: ["pytest", "tests/", "-v", "--tb=short"]
    depends_on:
      - db

  data_downloader:
    container_name: asi_downloader_test
    build:
      context: ./data_downloader
      dockerfile: Dockerfile.dev
    volumes:
      - ./data_downloader:/app
    command: ["pytest", "tests/", "-v", "--tb=short"]
    depends_on:
      - db

  frontend:
    profiles: ["donotstart"]
